services:
  database:
    image: mysql:8
    container_name: sgu-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sgu-demo
    ports:
      - "3307:3306"
    volumes:
      - sgu-volume:/var/lib/mysql
    networks:
      - sgu-net
    restart: unless-stopped

  frontend:
    image: client:1.0-sgu
    build:
      context: ./client
      args:
        API_HOST: localhost
        API_PORT: 8081
        API_BASE: /api/usuarios
        API_PROTOCOL: https
    container_name: sgu-frontend
    ports:
      - "80:80"
      - "3000:443"
    networks:
      - sgu-net
    volumes:
    - certbot-conf:/etc/letsencrypt:ro
    depends_on:
      - database

  backend:
    image: server:1.0-sgu
    build: 
      context: ./server
    environment:
      SERVER_PORT: 8080
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: sgu-demo 
      DB_USER: root
      DB_PASS: root
      SERVER_SSL_ENABLED: true
      SERVER_SSL_KEY_STORE: /etc/letsencrypt/live/localhost/keystore.p12
      SERVER_SSL_KEY_STORE_PASS: changeit
    container_name: sgu-backend
    ports:
      - "8081:8080"
    networks:
      - sgu-net
    volumes:
      - certbot-conf:/etc/letsencrypt:ro
    depends_on:
      - database

volumes:
  sgu-volume:
    external: true
  certbot-conf:
    external: true

networks:
  sgu-net:
      external: true

